"""add_regions_table

Revision ID: ca8b25d4b87b
Revises: 8b3dafedf964
Create Date: 2026-02-05 03:01:19.782317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'ca8b25d4b87b'
down_revision: Union[str, None] = '8b3dafedf964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # regions 테이블이 이미 존재하는지 확인 (init.sql 또는 이전 배포에서 생성된 경우)
    conn = op.get_bind()
    result = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables
            WHERE table_schema = 'public' AND table_name = 'regions'
        )
    """))
    table_exists = result.scalar()

    if not table_exists:
        op.create_table('regions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('layer', sa.String(length=100), nullable=True),
        sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=5179, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )

    # 인덱스도 존재 확인 후 생성
    result = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM pg_indexes WHERE indexname = 'idx_regions_geom'
        )
    """))
    index_exists = result.scalar()

    if not index_exists:
        op.create_index('idx_regions_geom', 'regions', ['geom'], unique=False, postgresql_using='gist')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_regions_geom', table_name='regions', postgresql_using='gist')
    op.drop_table('regions')
    # ### end Alembic commands ###
